// Re-vendors the file-type SVGs from vscode-icons at a pinned commit: node packages/ui/src/file-icons/vendor.mjs
// Writes svg/*.svg (what ships) and svgs.ts (the same markup as strings, so the unit needs no bundler loader).
import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

export const PACK = { name: 'vscode-icons', version: '12.19.0', commit: 'd2fc92ede72121115e17daf4db40afef6b2c22e4' }

/** Pack file name → the recorded edits (see LICENSE). An ink edit swaps a fill that vanishes on one theme for the text colour. */
const ICONS = {
  default_file: [['#c5c5c5', 'currentColor']],
  default_folder: [],
  file_type_audio: [['#00007f', 'currentColor']],
  file_type_avif: [['<path d="M8.309', '<path style="fill:currentColor" d="M8.309']],
  file_type_epub: [],
  file_type_excel: [],
  file_type_html: [],
  file_type_image: [],
  file_type_json: [],
  file_type_libreoffice_calc: [],
  file_type_libreoffice_impress: [],
  file_type_libreoffice_writer: [],
  file_type_markdown: [['#755838', 'currentColor']],
  file_type_pdf2: [],
  file_type_powerpoint: [],
  file_type_svg: [],
  file_type_text: [['#c2c2c2', 'currentColor']],
  file_type_video: [],
  file_type_word: [],
  file_type_xml: [],
  file_type_zip: [],
}

const here = dirname(fileURLToPath(import.meta.url))
const key = (file) => file.replace(/^file_type_/, '')
const out = {}

for (const [file, edits] of Object.entries(ICONS)) {
  const res = await fetch(`https://raw.githubusercontent.com/vscode-icons/vscode-icons/${PACK.commit}/icons/${file}.svg`)
  if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`)
  let svg = (await res.text()).replace(/<title>[^<]*<\/title>/, '').trim()
  for (const [from, to] of edits) {
    if (!svg.includes(from)) throw new Error(`${file}: edit target ${from} not found`)
    svg = svg.split(from).join(to)
  }
  await writeFile(join(here, 'svg', `${file}.svg`), svg + '\n')
  out[key(file)] = svg
}

const body = Object.entries(out)
  .map(([k, svg]) => `  ${k}: ${JSON.stringify(svg)},`)
  .join('\n')
await writeFile(
  join(here, 'svgs.ts'),
  `// Generated by vendor.mjs, the same markup as svg/*.svg. vscode-icons ${PACK.version} (${PACK.commit}), MIT: see LICENSE.\nexport const FILE_ICON_SVGS = {\n${body}\n} as const\n\nexport type FileIconName = keyof typeof FILE_ICON_SVGS\n`,
)
console.log(`vendored ${Object.keys(out).length} icons`)
